const express=require('express')
const app=express()
const cors=require('cors')
require('./connect')
const bodyParser=require('body-parser')
const adminRouter=require('./Router/adminRouter')
app.use(cors())
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
app.use('/admin',adminRouter)
app.listen(5000,()=>{
    console.log("port is listening to 5000")
})